name: Test Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npx jest
