name: Check formatting via prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  check-formatting-via-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check prettier
        run: npx prettier --check .
