name: Release zip file

# Which event cause workflow
on:
  push:
    branches:
      - main
  pull_request: # Merged PRs to main
    branches:
      - main
    types:
      - closed

jobs:
  release-zip:
    if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist folder as zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Upload as artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.zip
          retention-days: 1

      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      - name: Download dist.zip as artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create release with dist zip
        id: final-release-step
        uses: softprops/action-gh-release@v2
        with:
          body: "This is an automatic release with the built distribution."
          files: dist

      - name: Output new release
        run: echo 'Released ${{ steps.final-release-step.outputs.id }} at ${{ steps.final-release-step.outputs.url }}'
