name: Release zip file

# Which event cause workflow
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request: # Merged PRs to main
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  release-zip:
    if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist folder as zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Upload as artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.zip
          retention-days: 1
          overwrite: true

      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      - name: Display structure of files
        run: ls -R

      # - name: Generate release tag
      #   id: tag
      #   run: |
      #     echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: 'Get Previous tag'
        id: previous-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: 'Get next minor version'
        id: next-version
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previous-tag.outputs.tag }}

      - name: Create release with dist zip
        id: final-release-step
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next-version.outputs.patch }}
          body: "This is an automatic release with the built distribution."
          files: dist.zip

      - name: Output new release
        run: echo 'Released ${{ steps.final-release-step.outputs.id }} at ${{ steps.final-release-step.outputs.url }}'
