name: Release zip file

# Which event cause workflow
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request: # Merged PRs to main
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  release-zip:
    if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist folder as zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Upload as artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.zip
          retention-days: 1
          overwrite: true

      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      - name: Display structure of files
        run: ls -R

      - name: Generate release tag
        id: get-version
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "## Current Version: $VERSION"
          echo ::set-output name=version_tag::$VERSION

      - name: Create release with dist zip
        id: final-release-step
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-version.outputs.version_tag }}
          body: "This is an automatic release with the built distribution."
          files: dist.zip

      - name: Output new release
        run: echo 'Released ${{ steps.final-release-step.outputs.id }} at ${{ steps.final-release-step.outputs.url }}'
